from __future__ import annotations

from uuid import UUID
from pydantic import BaseModel, Field
from typing import Any, Literal

from app.common.literals import IterableJobStatus
from app.queries.errors import InvalidQueriesRequestError
from app.common.config import GLOBAL_SETTINGS, GLOBAL_CLIENT
from app.common.errors import InvalidModelIDError, ResponseEmptyError


class ModelQueryResponse(BaseModel):
    """A single query generated by the query generator."""
    number: int = Field(..., description="The number of the query")
    query: str = Field(..., description="The single query")


class ModelQueriesResponse(BaseModel):
    """A list of queries generated by the query generator."""
    queries: list[ModelQueryResponse] = Field(..., description="The list of queries")


class QueriesResponse(BaseModel):
    """ModelQueriesResponse wrapper containing the category for saving or returning to a client."""
    category: str
    queries: list[ModelQueryResponse]


class QueriesJSONLEntry(BaseModel):
    """A JSONL entry for a query."""
    model_id: str
    category: str
    number: int
    query: str


class QueriesGenerationRequest(BaseModel):
    """A request to generate a query, sent by the client."""

    categories: list[str]
    queries_per_category: int
    max_retries: int
    on_error: Literal["continue", "stop"]
    model_id: str | None = None

    def model_post_init(self, __context: Any) -> None:
        if len(self.categories) == 0:
            raise InvalidQueriesRequestError(
                reason="len(categories) cannot be 0"
            )
        
        if self.queries_per_category <= 0 or self.queries_per_category > 100:
            raise InvalidQueriesRequestError(
                reason="queries per category must be > 0 and <= 100"
            )
        
        if self.max_retries < 0 or self.max_retries > 10:
            raise InvalidQueriesRequestError(
                reason="max_retries must be >=0 and <=10"
            )
        
        for c in self.categories:
            if len(c) == 0:
                raise InvalidQueriesRequestError(
                    reason="found a blank category"
                )

        if self.model_id and self.model_id not in [m.id for m in GLOBAL_CLIENT.models.list()]:
                raise InvalidModelIDError(self.model_id)
    
    def initialize_job(self) -> QueriesGenerationJob:
        return QueriesGenerationJob(
            categories=self.categories,
            queries_per_category=self.queries_per_category,
            max_retries=self.max_retries,
            on_error=self.on_error,
            model_id=self.model_id if self.model_id else GLOBAL_SETTINGS.model_id,
            status="pending",
            error_detail=None,
            response=None
        )


class QueriesGenerationJob(QueriesGenerationRequest):
    model_id: str
    status: IterableJobStatus
    error_detail: str | None = None
    response: list[QueriesResponse] | None = None

    def save(
        self,
        format: Literal["json", "jsonl"],
        uuid: UUID
    ) -> None:
        save_path = GLOBAL_SETTINGS.save_dir / f"{str(uuid)}.{format}"
        with open(save_path, 'w') as save_file:
            if format == "json": save_file.write(self.model_dump_json(indent=2))
            elif format == "jsonl":
                if not self.response: raise ResponseEmptyError(str(uuid))
                for c in self.response:
                    for q in c.queries:
                        save_file.write(QueriesJSONLEntry(
                            model_id=self.model_id,
                            category=c.category,
                            number=q.number,
                            query=q.query
                        ).model_dump_json() + "\n")