from __future__ import annotations

from pydantic import BaseModel, Field, ValidationError
from typing import Any

from app.common.config import GLOBAL_CLIENT, GLOBAL_SETTINGS
from app.common.literals import JobStatus, OnError, SaveFormat
from app.queries.errors import InvalidQueriesJobRequest
from app.common.chats import Chat, ChatMessage
from app.common.errors import (
    InvalidModelIDError,
    SaveFileNotFoundError,
    CorrupedSaveFileError,
    JobEmptyError
)


class QueryResponse(BaseModel):
    """A query generated by the queries generator."""
    number: int = Field(..., description="The index of the query in the list of queries")
    query: str = Field(..., description="The single query")

    def to_chats(self, system_messages: list[str] | None = None) -> list[Chat]:
        chats: list[Chat] = []
        if system_messages:
            for system_message in system_messages:
                chats.append(Chat(
                    complete=False,
                    messages=[
                        ChatMessage(
                            role="system",
                            content=system_message
                        ),
                        ChatMessage(
                            role="user",
                            content=self.query
                        )
                    ]
                ))
            return chats
        return [Chat(
            complete=False,
            messages=[
                ChatMessage(
                    role="user",
                    content=self.query
                )
            ]
        )]


class QueriesResponse(BaseModel):
    """A list of queries generated by the queries generator."""
    queries: list[QueryResponse] = Field(..., description="The list of queries")

    def to_chats(self, system_messages: list[str] | None = None) -> list[Chat]:
        chats: list[Chat] = []
        for query in self.queries:
            chats.extend(query.to_chats(system_messages))
        return chats


class QueryJSONLEntry(BaseModel):
    model_id: str
    number: int
    query: str


class QueriesJobRequest(BaseModel):
    categories: list[str]
    queries_per_category: int
    max_retries: int = 3
    on_error: OnError = "continue"
    model_id: str = GLOBAL_SETTINGS.default_model_id

    def model_post_init(self, __context: Any) -> None:
        if len(self.categories) == 0:
            raise InvalidQueriesJobRequest(
                reason="len(categories) cannot be 0"
            )
        for i, category in enumerate(self.categories):
            if len(category) == 0:
                raise InvalidQueriesJobRequest(
                    reason=f"category {i} is empty"
                )
        if self.max_retries < 0:
            raise InvalidQueriesJobRequest(
                reason="max_retries must be either 0 or a positive integer"
            )
        if self.model_id not in [m.id for m in GLOBAL_CLIENT.models.list()]:
            raise InvalidModelIDError(self.model_id)
        
    def initialize_job(self) -> QueriesJob:
        return QueriesJob(
            categories=self.categories,
            queries_per_category=self.queries_per_category,
            max_retries=self.max_retries,
            on_error=self.on_error,
            model_id=self.model_id,
            status="pending",
            error_detail=None,
            result=None
        )
    

class QueriesJob(QueriesJobRequest):
    status: JobStatus
    error_detail: str | None = None
    result: list[QueriesResponse] | None = None

    def to_chats(self, system_messages: list[str] | None = None) -> list[Chat]:
        if not self.result: return []
        chats: list[Chat] = []
        for response in self.result:
            chats.extend(response.to_chats(system_messages=system_messages))
        return chats
    
    def save(self, uuid_str: str, format: SaveFormat) -> None:
        save_path = GLOBAL_SETTINGS.save_dir / f"{uuid_str}.{format}"
        with open(save_path, 'w') as save_file:
            if format == "json":
                save_file.write(self.model_dump_json(indent=2))
            elif format == "jsonl":
                if not self.result:
                    raise JobEmptyError(uuid_str)
                for queries in self.result:
                    for query in queries.queries:
                        entry = QueryJSONLEntry(
                            model_id=self.model_id,
                            number=query.number,
                            query=query.query
                        )
                        save_file.write(entry.model_dump_json() + "\n")
    
    @classmethod
    def load(cls, uuid_str: str) -> "QueriesJob":
        load_path = GLOBAL_SETTINGS.save_dir / f"{uuid_str}.json"
        if not load_path.exists():
            raise SaveFileNotFoundError(str(load_path))
        with open(load_path, 'r') as load_file:
            try:
                return QueriesJob.model_validate_json(load_file.read())
            except ValidationError:
                raise CorrupedSaveFileError(str(load_path))